### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by ctty11** [kiedtl/bunnywm#1]
types.h is missing

**Comment by kiedtl** [comment]
On 21-10-14 06:39 , ctty11 wrote:
> types.h is missing
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kiedtl/bunnywm/issues/1

Did you clone with '--recurse'? `types.h` is included in a git submodule.

If you haven't, try:

```
git submodule init
git submodule update
```

**Comment by ghost** [comment]
```cc -O3 -std=c99 -Wall -Wextra -pedantic -Wmissing-prototypes -Wold-style-definition -Werror -Wno-incompatible-pointer-types -Isub/ccommon/ -I/usr/include/X11/ -I/usr/include/    -c -o bunny.o bunny.c
bunny.c:422:1: error: ‘run’ defined but not used [-Werror=unused-function]
  422 | run (const Arg arg)
      | ^~~
cc1: all warnings being treated as errors
make: *** [<builtin>: bunny.o] Error 1
```

**Comment by kiedtl** [comment]
You can edit the Makefile to remove Werror and see if it builds then. At this point I unfortunately have no time to look into this, so I can't help you further.
